version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/user/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/user/nginx/sites-available:/etc/nginx/sites-available
      - /home/user/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /home/user/nginx/ssl:/etc/nginx/ssl
      - /home/user/nginx/logs:/var/log/nginx
    depends_on:
      - wordpress
    networks:
      - shop_network

  wordpress:
#    build: .
    image: taranovpetryxa/web_shop:latest
    container_name: shop_web
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_db_user
      WORDPRESS_DB_PASSWORD: cd!995
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - shop_network

  db:
    image: mysql:latest
    container_name: shop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cd!995
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_db_user
      MYSQL_PASSWORD: cd!995
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - shop_network

node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - shop_network
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: unless-stopped
#    environment:
#      PMA_HOST: db
#      PMA_USER: root
#      PMA_PASSWORD: cd!995
#    ports:
#      - "88:80"
#    networks:
#      - shop_network


volumes:
  db_data:
  html:

networks:
  shop_network:
    driver: bridge
